doctrine:
    dbal:
        connections:
            pgsql:
                driver: 'pdo_pgsql'
                user: 'postgres'
                password: 'root'
                port: '5432'
                dbname: 'sionic-test-task'
                host: '/var/run/postgresql'
                charset: 'UTF8'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
